using EmployeePayrollADO.Net;
Repos repos = new Repos();
string my = repos.GetAllEmployee();
Console.WriteLine(my);
repos.UpdateDataOfEmployee();
repos.RetrieveDataByName();
repos.RetrieveDataBetweenDateOfJoin();
repos.AddEmployeePayrollData();
SalaryOfEmployee employee = new SalaryOfEmployee();
employee.FindSumOfsalaryOfMale();
employee.SumOfSalaryOfFemaleEmp();
employee.FindAvgOfsalaryOfMale();
employee.AvgOfSalaryOfFemaleEmp();
employee.MinSalaryOfFemaleEmp();
employee.FindMinOfsalaryOfMale();
employee.MaxSalaryOfFemaleEmp();
employee.FindMaxsalaryOfMale();
employee.CountOfFemaleEmp();
employee.CountOfMaleEmployee();